name: "Manage JIRA release"
description: "Creates or updates a JIRA version and adds the issues mentioned in the changelog"
inputs:
    host:
        description: "Your atlassian host i.e. myhost.atlassian.net"
        required: true

    project-key:
        description: "Create release under the project with this key. i.e. MYPROJ"
        required: true

    release-name:
        description: "The JIRA version/release name. i.e. MyPackage 1.2.3"
        required: true

    release-description:
        description: "The JIRA release description. i.e. My awesome release"
        required: true

    release-changelog:
        description: "The changelog will be parsed for JIRA issues mentioned and the fix version will be set on those issues"
        required: true

runs:
    using: "node16"
    main: "../jira-client/dist/releaseAction.js"
