name: "Check JIRA issue reference"
description: "Checks if PR has a reference to a valid jira ticket"
inputs:
    host:
        description: "Your atlassian host  i.e. myhost.atlassian.net"
        required: true

    project-key:
        description: "check jiras under the project with this key. i.e. MYPROJ"
        required: true

runs:
    using: "node16"
    main: "../jira-client/dist/checkPRAction.js"
