name: "Check JIRA issue reference"
description: "Checks if PR has a reference to a valid jira ticket"
inputs:
    host:
        description: "Your atlassian host  i.e. myhost.atlassian.net"
        required: true

    project-key:
        description: "check jiras under the project with this key. i.e. MYPROJ"
        required: true

    bypass-prefix:
        description: "Prefix the title of the PR with this text to skip the check. Do not provide this if you require PR to always have an existing JIRA issue in the title. For example: [NOJIRA]"
        required: false

runs:
    using: "node16"
    main: "../../jira-client/dist/checkPRAction.min.js"
